apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
      metallb.universe.tf/allow-shared-ip: svcs
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - port: 5050
      targetPort: 5050
  selector:
    app: wordpress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress-image
        name: wordpress
        imagePullPolicy: Never
        env:
        - name: DB_NAME
          value: wordpress
        - name: DB_HOST
          value: mysql-svc
        - name: DB_USER
          value: mysql
        - name: DB_PASS
          value: pass
        ports:
        - containerPort: 5050
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
