FROM alpine:latest

# Update and install
RUN apk update && apk upgrade
RUN apk add wget

RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.16.3_linux_amd64.tar.gz
RUN tar xf telegraf-1.16.3_linux_amd64.tar.gz
RUN cp -a telegraf-1.16.3/. /
COPY ./telegraf.conf	/etc/telegraf/telegraf.conf

EXPOSE 8086

ENTRYPOINT	/usr/bin/telegraf --config /etc/telegraf/telegraf.conf
